:syntax on
:set number
:set modeline
:set list
:set lcs=tab:>-,eol:$

:set tabstop=8
:set expandtab
:set shiftwidth=4
:set softtabstop=4

:set backspace=indent,eol,start

call pathogen#infect()

if has('nvim')
    runtime! python_setup.vim
endif

let g:jedi#use_tabs_not_buffers = 0
