:syntax on
:set number
:set modeline
:set list
:set lcs=tab:>-,eol:¬,trail:▒

:set tabstop=8
:set expandtab
:set shiftwidth=4
:set softtabstop=4

:set backspace=indent,eol,start

call pathogen#infect()

if has('nvim')
    runtime! python_setup.vim
endif

filetype plugin on
filetype indent on

map <C-F11> :!ctags -R -f $VIRTUAL_ENV/tags $VIRTUAL_ENV/lib/python2.7/site-packages<CT>
set tags=$VIRTUAL_ENV/tags

