# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
unsetopt beep
bindkey -e
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/lyndsy/.zshrc'

# Docker
alias dm="docker-machine"
alias dc="docker-compose"

# tmuxinator
export EDITOR=vim
which tmuxinator > /dev/null 2>&1
if [ $? = 0 ]
then
    alias t='tmuxinator'
fi

# Add completions directory to fpath, so zsh sees it
fpath=(~/.config/zsh/completions $fpath)

autoload -Uz compinit
compinit
# End of lines added by compinstall

compdef _invoke invoke
compdef _invoke inv

# Begin Lyndsy's edits
######################

# Set path to include:
#   * Homebrew
export PATH=/usr/local/bin:~/.bin:$PATH

# Enable syntax highlighting a'la Fish
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Prompts
setopt promptsubst
source ~/.config/zsh/prompt/zshprompt.zsh

# Python setup for OSX
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
source /usr/local/bin/virtualenvwrapper.sh
export PIP_REQUIRE_VIRTUALENV=true
export PIP_CERT=~/.config/ssl/certs/DigiCertHighAssuranceEVRootCA.pem

# Aliases
which lolcat > /dev/null 2>&1
if [ $? = 0 ]
then
    alias cat='lolcat'
fi

alias fucking='sudo'

# - Development

alias g='git '
alias i='invoke'
alias v='vagrant'

# - Python virtual environments

alias d='deactivate'
alias mkv='mkvirtualenv'
alias rmv='rmvirtualenv'
alias wo='workon'

# Make the delete key work (WTF doesn't it by default!?)
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey ';5D' backward-word
bindkey ';5C' forward-word

# Ruby gems
export PATH=/usr/local/opt/ruby/bin:$PATH

# Postgres config (development)
export PGDATA=/usr/local/var/postgres
# Terminal application config envvars

export GREP_OPTIONS='--color=auto'

# Set up Java for OSX Mavericks
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
